@startuml
participant "controller: Controller" as C
participant "view: View" as V
participant "viewLogin: ViewLogin" as L
participant ": Utils" as U
participant "model: CompoStore" as s
participant "Cliente: Cliente" as u

C -> V : 1. menuBegin()

activate C

activate V
V-->C : 2
deactivate V

C -> V : 2. menuLogin()

activate V
V-->C : 3
deactivate V
C -> L : 3. insertCredentials()
activate L
L -> U : 3.1. getString()
activate U
U --> L : username
deactivate U
L -> U : 3.2. getString()
activate U
U --> L : password
deactivate U
L -> u : <<verify>>
deactivate L
C -> s : 4. getClienteList()
s --> C : clienteList()
C -> u : 5. Login()
u --> C : menuCliente

deactivate L
@enduml