@startuml
actor Cliente as c
participant "Sistema" as s

c-> s: 1.Insere o nome de Utilizador
c-> s: 2. Insere uma password
s-> s: 2.1. Verifica se o utilizador já está a ser utilizado
s-> s: 2.2. Verifica se a password é segura
alt
    alt "Sessão Iniciada: true":
        s --> c: Return success
    else "Sessão Iniciada: false":
        s --> c: Return failure
end
@enduml