@startuml
actor Cliente as c
participant "Sistema" as s

c -> s: 1. Ver o carrinho de compras
s -> s: 1.1. Verifica se existe algum produto no carrinho
s --> c: 2. Mostra o carrinho
alt
  alt "Apresentar o carinho: true"
    s --> c: return success
  else "Apresentar o carinho: false"
    s --> c: return failure
end
@enduml